name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: check branch
        run: |
          $branchs = git branch --contains $env:GITHUB_REF
          $branchsArray = $branchs -split ' '
          foreach ($branch in $branchsArray) {
            if ($branch -eq 'main') {
              exit 0
            }
          }
          exit 1
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: '3.11'
          enable-pep582: false
      - name: Install dependencies
        run: pdm install
      - name: build binary
        run: echo "Yes" | pdm nuitka
      - name: make zip
        run: |
          $tag = $env:GITHUB_REF -replace 'refs/tags/', ''
          $tag = $tag -replace '^v', ''
          $zip = "ojichat$tag-windows.zip"
          $files = "ojichat.exe", "README.md", "CREDITS.md", "LICENSE"
          Compress-Archive -Path $files -DestinationPath $zip
      - name: run binary
        run: .\ojichat.exe
      - name: update release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: ojichat*.zip
